import Head from "next/head";
import React, { useState, useEffect } from "react";
import ModalAddGift from "../components/ModalAddGift";
import ListGifts from "../components/ListGifts";
import AddGift from "../components/AddGift";

export default function Home() {
  const [gifts, setGifts] = useState<{ id: number }[]>([]);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    let taskEditing = JSON.parse(localStorage.getItem("gifts") || "[]");
    setGifts(taskEditing ? taskEditing : []);
  }, []);

  const addGifts = (items: object) => {
    const id: number = Math.floor(Math.random() * 1000) + 1;
    try {
      setGifts([{ id, ...items }, ...gifts]);
      window.localStorage.setItem(
        "gifts",
        JSON.stringify([{ id, ...items }, ...gifts])
      );
    } catch (e) {
      console.error(e);
    }
  };
  //console.log(gifts);

  const deleteGift = (id: any) => {
    setGifts(gifts.filter((el) => id !== el.id));
    window.localStorage.setItem("gifts", JSON.stringify(gifts));
  };

  const deleteAll = (id: any) => {
    setGifts(gifts.filter((el) => id === el.id));
    window.localStorage.setItem("gifts", JSON.stringify([]));
  };

  return (
    <div>
      <Head>
        <title>Chritmas Advency (AngelaG)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full mt-20">
        <div className="flex space-x-8 md:justify-between">
          <h1>Chritmas List:</h1>
          <button
            onClick={() => setOpen(true)}
            className="bg-green-500 p-3 rounded-lg"
          >
            Add Gift
          </button>
        </div>

        {/* */}
        <ModalAddGift open={open} setOpen={setOpen}>
          <AddGift addGifts={addGifts} gifts={gifts} />
        </ModalAddGift>

        <div className="flex flex-col justify-between h-96 w-[250px] sm:w-[320px] overflow-auto p-4 m-4 bg-neutral-700 rounded-md">
          {gifts.length === 0 ? (
            <p className="pt-4">Oh no! The list is empty!</p>
          ) : (
            gifts.map((gift: any) => (
              <div key={gift.id}>
                <ListGifts gift={gift} deleteGift={deleteGift} />
              </div>
            ))
          )}
          <button
            onClick={deleteAll}
            className="self-center w-full rounded-lg border-2 bg-red-600 border-red-700 p-2 m-4 focus:ring-red-500"
          >
            Delete all
          </button>
        </div>
      </main>
    </div>
  );
}
