import Head from "next/head";
import React, { useState, useEffect } from "react";
import ModalAddGift from "../components/ModalAddGift";
import ListGifts from "../components/ListGifts";
import AddGift from "../components/AddGift";
import { GiftsTypes } from "../types";

export default function Home() {
  const [gifts, setGifts] = useState<GiftsTypes[]>([]);
  const [open, setOpen] = useState(false);
  const [edit, setEdit] = useState("");

  useEffect(() => {
    let setInLocalStorage = JSON.parse(localStorage.getItem("gifts") || "[]");
    setGifts(setInLocalStorage ? setInLocalStorage : []);
  }, []);

  console.log(gifts);
  const deleteGift = (id: any) => {
    try {
      setGifts(gifts.filter((el) => id !== el.id));
      window.localStorage.setItem("gifts", JSON.stringify(gifts));
    } catch (e) {
      console.error(e);
    }
  };

  const deleteAll = () => {
    setGifts([]);
    window.localStorage.setItem("gifts", JSON.stringify([]));
  };

  return (
    <div>
      <Head>
        <title>Chritmas Advency (AngelaG)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="w-full mt-20">
        <div className="flex space-x-8 md:justify-between mb-4 items-center ">
          <h1 className="font-titleH1 text-4xl md:text-5xl">Christmas List:</h1>
          <button
            onClick={() => setOpen(true)}
            className="bg-green-500 p-2 rounded-lg h-max"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-4 w-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 4v16m8-8H4"
              />
            </svg>
          </button>
        </div>

        {/* */}
        <ModalAddGift open={open} setOpen={setOpen}>
          <AddGift
            edit={edit}
            setEdit={setEdit}
            gifts={gifts}
            setGifts={setGifts}
            setOpen={setOpen}
          />
        </ModalAddGift>

        <div className="flex flex-col justify-between h-[450px] w-[340px] md:w-[400px] overflow-auto p-4 bg-neutral-700 rounded-md">
          {gifts.length === 0 ? (
            <p className="pt-4 text-center">Oh no! The list is empty!</p>
          ) : (
            gifts.map((gift: any) => {
              return (
                <div key={gift.id}>
                  <ListGifts
                    gift={gift}
                    deleteGift={deleteGift}
                    setEdit={setEdit}
                    open={open}
                    setOpen={setOpen}
                  />
                </div>
              );
            })
          )}

          {gifts.length >= 2 ? (
            <button
              onClick={deleteAll}
              className="self-center w-full mt-6 text-black rounded-lg bg-gray-300 p-2 focus:outline-none"
            >
              Delete all
            </button>
          ) : (
            ""
          )}
        </div>
      </main>
    </div>
  );
}
