import Head from "next/head";
import React, { useState } from "react";
import ListGifts from "../components/ListGifts";
import AddGift from "../components/AddGift";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chritmas Advency (Angela)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Regalos:</h1>
        <AddGift />
        <ListGifts />
      </main>
    </div>
  );
}
